src/Entity/Reclamation.php
<?php

namespace App\Entity;
use App\Entity\Categorie;
use App\Repository\ReclamationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\ORM\Mapping\AnsiQuoteStrategy;


#[ORM\Entity(repositoryClass: ReclamationRepository::class)]
#[ORM\Index(columns:['id_Categorie'],name:'fk_categorie')]
class Reclamation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[ORM\ManyToOne(targetEntity: Categorie::class,inversedBy: 'reclamations')]

    private ?int $id_rec = null;

    #[ORM\Column(length: 255)]
    private ?string $fullname_rec_s = null;

    #[ORM\Column(length: 255)]
    private ?string $fullname_rec_r = null;


    #[ORM\JoinColumn(name:'id_Categorie',referencedColumnName:'id_categorie')]
    #[ORM\ManyToOne(targetEntity: 'Categorie')]
    private Categorie $categorie ;


    #[ORM\Column(length: 255)]
    private ?string $mail = null;

    #[ORM\Column(length: 255)]
    private ?string $num_tel = null;

    #[ORM\Column(length: 1500)]
    private ?string $text_rec = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_de_rec = null;

    public function getId(): ?int
    {
        return $this->id_rec;
    }

    public function getFullnameRecS(): ?string
    {
        return $this->fullname_rec_s;
    }

    public function setFullnameRecS(string $fullname_rec_s): self
    {
        $this->fullname_rec_s = $fullname_rec_s;

        return $this;
    }

    public function getFullnameRecR(): ?string
    {
        return $this->fullname_rec_r;
    }

    public function setFullnameRecR(string $fullname_rec_r): self
    {
        $this->fullname_rec_r = $fullname_rec_r;

        return $this;
    }
/*
    public function getIdCategorie(): ?Categorie
    {
        return $this->id_categorie;
    }

    public function setIdCategorie(?Categorie $id_categorie): self
    {
        $this->id_categorie = $id_categorie;

        return $this;
    }
*/
    /**
     * @return Categorie
     */
    public function getCategorie():Categorie
    {

        return $this->categorie;
    }

    /**
     * @param Categorie $categorie

     */
    public function setCategorie(Categorie $categorie):void
    {
        $this->categorie=$categorie;
    }
    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getNumTel(): ?string
    {
        return $this->num_tel;
    }

    public function setNumTel(string $num_tel): self
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    public function getTextRec(): ?string
    {
        return $this->text_rec;
    }

    public function setTextRec(string $text_rec): self
    {
        $this->text_rec = $text_rec;

        return $this;
    }

    public function getDateDeRec(): ?\DateTimeInterface
    {
        return $this->date_de_rec;
    }

    public function setDateDeRec(\DateTimeInterface $date_de_rec): self
    {
        $this->date_de_rec = $date_de_rec;

        return $this;
    }
}

src/Form/ReclamationType.php
<?php

namespace App\Form;

use App\Entity\Reclamation;
use App\Entity\Categorie;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class ReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('fullname_rec_s')
            ->add('fullname_rec_r')
            ->add('Categorie',EntityType::class,[

                'class'=> Categorie::class,
                'choice_label'=>'nom_Categorie',
            ])
            ->add('mail')
            ->add('num_tel')
            ->add('text_rec')
            ->add('date_de_rec')
           
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reclamation::class,
        ]);
    }
}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;

use App\Class\Search;
use App\Entity\Reclamation;
use App\Entity\Mail;
use App\Form\ReclamationType;
use App\Form\SearchType;
use App\Repository\CategorieRepository;
use App\Repository\ReclamationRepository;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/reclamation')]
class ReclamationController extends AbstractController
{
    private $entityManager;
    public function __construct(EntityManagerInterface $entityManager){
        $this->entityManager=$entityManager;
    }

    #[Route('/showw', name: 'app_reclamation', methods: ['GET'])]
    public function index(Request $request): Response
    {
        $reclamation = $this->entityManager->getRepository(Reclamation::class)->findAll();
        $search= new Search();
        $form=$this->createForm(SearchType::class,$search);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $reclamation = $this->entityManager->getRepository(Reclamation::class)->findwithSearch($search);

        }
        return $this->render('reclamation/index.html.twig', [
            'reclamations'=>$reclamation,

            'form'=>$form->createView()
        ]);
    }

    #[Route('/new', name: 'app_reclamation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ReclamationRepository $reclamationRepository,CategorieRepository $categorieRepository): Response
    {
        $reclamation = new Reclamation();
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reclamationRepository->save($reclamation, true);
            $mail = new Mail();
            $content="Bonjour ".$reclamation->getFullnameRecS()."<br/>Bienvenue sur UpServe.<br><br/>Nous avons bien reçu votre réclamation. Nous sommes sincèrement désolés pour ce désagrément. Nous mettons tout en œuvre pour résoudre ce problème au plus vite ";
        $mail->send($reclamation->getMail(),$reclamation->getFullnameRecS(),'mon premier mail',$content);

            return $this->redirectToRoute('app_reclamation', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reclamation/new.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reclamation_show', methods: ['GET'])]
    public function show(Reclamation $reclamation): Response
    {
        return $this->render('reclamation/show.html.twig', [
            'reclamation' => $reclamation,
        ]);
    }
    ///search
    #[Route('/filtrage', name: 'app_reclamation_filtrer', methods: ['GET'])]
    public function indexx(ReclamationRepository $reclamationRepository): Response
    {
        return $this->render('reclamation/search.html.twig');
    }


    ////////stat
    #[Route('/stat/s/s', name: 'app_reclamation_stat', methods: ['GET'])]
    public function statistiques(ReclamationRepository $reclamationRepository): Response
    {
       // $ca=$reclamationRepository->countAvis();

        $cf=$reclamationRepository->countfeedback();

       // $cs=$reclamationRepository->countMauvaisService();

        return $this->render('statistique.html.twig', [

            //'ca'=>$ca,
            'cf'=>$cf,
            //'cs'=>$cs,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_reclamation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Reclamation $reclamation, ReclamationRepository $reclamationRepository): Response
    {
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $reclamationRepository->save($reclamation, true);

            return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reclamation/edit.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_reclamation_delete', methods: ['POST'])]
    public function delete(Request $request, Reclamation $reclamation, ReclamationRepository $reclamationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reclamation->getId(), $request->request->get('_token'))) {
            $reclamationRepository->remove($reclamation, true);
        }

        return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/reclamation/_delete_form.html.twig
<form method="post" action="{{ path('app_reclamation_delete', {'id': reclamation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reclamation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/reclamation/edit.html.twig
{% extends 'base.html.twig' %}
{% block sidebar %}
{% endblock %}
{% block section %}
    <h1>Edit Reclamation</h1>

    {{ include('reclamation/_form.html.twig', {'button_label': 'Update'}) }}

    <button class="btn btn-outline-secondary"><a href="{{ path('app_reclamation') }}">back</a></button>

    {{ include('reclamation/_delete_form.html.twig') }}
{% endblock %}

templates/reclamation/index.html.twig
{% extends 'base.html.twig' %}
{% block sidebar %}
{% endblock %}
{% block section %}
    <h1>Reclamation</h1>
<div class="row">
    <div class="col-3">
        <h1>Filtrer</h1>
        {{  form(form) }}
    </div>
</div>
    <div>

            <table class="table">
                <div class="col-9">
                     <thead>
                        <tr>

                            <th style="color: #0a58ca">NOM DE CLIENT</th>
                            <th style="color: #0a58ca">NOM D'EMPLOYE</th>
                            <th style="color: #0a58ca">CATEGORIE</th>
                            <th style="color: #0a58ca">EMAIL</th>
                            <th style="color: #0a58ca">NUMERO TELEPHONE</th>
                            <th style="color: #0a58ca">TEXTE DE RECLAMATION</th>
                            <th style="color: #0a58ca">DATE DE RECLAMATION</th>
                            <th style="color: #0a58ca">ACTION</th>
                    </tr>
                </thead>
                </div>
        <tbody>

            {% for reclamation in reclamations %}
                <tr>

                    <td>{{ reclamation.fullnameRecS }}</td>
                    <td>{{ reclamation.fullnameRecR }}</td>
                    <td>{{ reclamation.Categorie.nomCategorie }}</td>
                    <td>{{ reclamation.mail }}</td>
                    <td>{{ reclamation.numTel }}</td>
                    <td>{{ reclamation.textRec }}</td>
                    <td>{{ reclamation.dateDeRec ? reclamation.dateDeRec|date('Y-m-d') : '' }}</td>
                    <td>
                        <button style="background-color: #008a00 "class="btn btn-outline-success"><a style="color: white"href="{{ path('app_reclamation_show', {'id': reclamation.id}) }}">Afficher</a></button><br/>
                        <button style="background-color: #a52834" class="btn btn-outline-dange"><a style="color: white" href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">Editer</a></button>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
    </table>
    </div>
    <button class="btn btn-outline-primary"> <a href="{{ path('app_reclamation_new') }}">Ajouter Reclamation</a></button>
{% endblock %}

templates/reclamation/new.html.twig
{% extends 'base.html.twig' %}
{% block sidebar %}
{% endblock %}
{% block section %}
    <h1>Ajouter Reclamation</h1>

    {{ include('reclamation/_form.html.twig') }}

    <button class="btn btn-outline-secondary"><a href="{{ path('app_reclamation') }}">back</a></button>
{% endblock %}

templates/reclamation/show.html.twig
{% extends 'base.html.twig' %}
{% block sidebar %}
{% endblock %}
{% block section %}
    <h1>Reclamation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reclamation.id }}</td>
            </tr>
            <tr>
                <th>Fullname_rec_s</th>
                <td>{{ reclamation.fullnameRecS }}</td>
            </tr>
            <tr>
                <th>Fullname_rec_r</th>
                <td>{{ reclamation.fullnameRecR }}</td>
            </tr>
            <tr>
                <th>Categori</th>
                <td>{{ reclamation.Categorie.nomCategorie }}</td>
            </tr>
            <tr>
                <th>Mail</th>
                <td>{{ reclamation.mail }}</td>
            </tr>
            <tr>
                <th>Num_tel</th>
                <td>{{ reclamation.numTel }}</td>
            </tr>
            <tr>
                <th>Text_rec</th>
                <td>{{ reclamation.textRec }}</td>
            </tr>
            <tr>
                <th>Date_de_rec</th>
                <td>{{ reclamation.dateDeRec ? reclamation.dateDeRec|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <button  class="btn btn-outline-secondary"><a style="color: black"href="{{ path('app_reclamation') }}">back</a></button>

    <button class="btn btn-primary"><a style="color: white" href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">Editer</a></button>

    {{ include('reclamation/_delete_form.html.twig') }}
{% endblock %}